/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package elistasmkiosco;

import java.util.ArrayList;

/**
 *
 * @author Piruxb17
 */
public class Principal extends javax.swing.JFrame {
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bg = new javax.swing.JPanel();
        bAgregarRubro = new javax.swing.JButton();
        bMostrarArticulos = new javax.swing.JButton();
        bMostrarRubros = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Bg.setBackground(new java.awt.Color(255, 255, 255));
        Bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bAgregarRubro.setBackground(new java.awt.Color(204, 255, 255));
        bAgregarRubro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bAgregarRubro.setText("Agregar Rubro");
        bAgregarRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarRubroActionPerformed(evt);
            }
        });
        Bg.add(bAgregarRubro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 150, 30));

        bMostrarArticulos.setBackground(new java.awt.Color(204, 255, 255));
        bMostrarArticulos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bMostrarArticulos.setText("Mostrar Articulos");
        bMostrarArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMostrarArticulosActionPerformed(evt);
            }
        });
        Bg.add(bMostrarArticulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 150, 30));

        bMostrarRubros.setBackground(new java.awt.Color(204, 255, 255));
        bMostrarRubros.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bMostrarRubros.setText("Mostrar Rubros");
        bMostrarRubros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMostrarRubrosActionPerformed(evt);
            }
        });
        Bg.add(bMostrarRubros, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 150, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/fondo2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        Bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 470, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAgregarRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarRubroActionPerformed
        agregarProductos vAgregarProductos= new agregarProductos();
        vAgregarProductos.setVisible(true);
    }//GEN-LAST:event_bAgregarRubroActionPerformed

    private void bMostrarArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMostrarArticulosActionPerformed
        mostrarArticulos vMostrarAritculos= new mostrarArticulos();
        vMostrarAritculos.setVisible(true);
    }//GEN-LAST:event_bMostrarArticulosActionPerformed

    private void bMostrarRubrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMostrarRubrosActionPerformed
        mostrarRubros vMostraRubros= new mostrarRubros();
        vMostraRubros.setVisible(true);
    }//GEN-LAST:event_bMostrarRubrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bg;
    private javax.swing.JButton bAgregarRubro;
    private javax.swing.JButton bMostrarArticulos;
    private javax.swing.JButton bMostrarRubros;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
